version: '3.8'

networks:
  scd-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:5000
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - scd-network

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/freefuel
      - JWT_SECRET=freefuel_secret
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - scd-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - scd-network

volumes:
  mongo-data: 