name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression
      shell: pwsh

    - name: Build Backend Docker image
      run: |
        cd server
        docker build -t durrani2600/freefuel-backend:latest .

    - name: Build Frontend Docker image
      run: |
        cd client
        docker build -t durrani2600/freefuel-frontend:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Backend Docker image
      run: docker push durrani2600/freefuel-backend:latest

    - name: Push Frontend Docker image
      run: docker push durrani2600/freefuel-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout restart deployment/frontend
        kubectl rollout restart deployment/backend
        kubectl rollout status deployment/frontend
        kubectl rollout status deployment/backend
